services:
    app_micro_auth:
        build: 
          args: 
              user: 'lucas-borges'
              uid: 1000 
          dockerfile: Dockerfile 
        container_name: app_micro_auth
        extra_hosts:
          - "host.docker.internal:host-gateway"
        environment:
          - DB_HOST=db_micro_auth
          - DB_DATABASE=micro-auth
          - DB_USERNAME=root
          - DB_PASSWORD=root
        volumes:
          - .:/var/www
        networks:
          - network-auth
        depends_on:
          - db_micro_auth
          - redis_micro_auth
          - queue_micro_auth

    nginx_micro_auth:
        build: .docker/nginx
        container_name: nginx_micro_auth
        restart: always
        tty: true
        ports:
          - "8090:80"
        volumes:
          - .:/var/www
        networks:
          - network-auth
        depends_on:
          - app_micro_auth
    
    queue_micro_auth:
        build: 
            args: 
                user: 'lucas-borges'
                uid: 1000
            dockerfile: Dockerfile
        container_name: queue_micro_auth    
        command: 'php artisan queue:work'
        restart: unless-stopped
        volumes: 
            - .:/var/www
        depends_on: 
            - redis_micro_auth
        networks: 
            - network-auth

    db_micro_auth:
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: db_micro_auth
        restart: always
        tty: true
        volumes:
          - ./.docker/dbdata:/var/lib/mysql
        environment:
          - MYSQL_DATABASE=micro-auth
          - MYSQL_ROOT_PASSWORD=root
        networks:
          - network-auth

    redis_micro_auth:
        image: redis:latest
        networks: 
            - network-auth

networks:
    network-auth:
        driver: bridge